{{- if not .Values.querydesk.configExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent.fullname" . }}
  labels:
    {{ include "agent.labels" . | nindent 4 }}
type: Opaque
data:
  config.json: {{ .Values.querydesk.config | b64enc | quote }}
{{- end }}