apiVersion: v1
kind: Service
metadata:
  name: {{ include "QueryDesk.fullname" . }}
  labels:
    {{- include "QueryDesk.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "QueryDesk.selectorLabels" . | nindent 4 }}
{{- if .Values.proxy.service.create }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "QueryDesk.fullname" . }}-proxy
  labels:
    {{- include "QueryDesk.labels" . | nindent 4 }}
spec:
  type: {{ .Values.proxy.service.type }}
  ports:
    - port: 5432
      targetPort: 54320
      {{- with .Values.proxy.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
      protocol: TCP
  selector:
    {{- include "QueryDesk.selectorLabels" $ | nindent 4 }}
{{- end }}